### ISSUE TITLE
Heavy memory usage causes the null field return value for SQL query. It causes the missing index.

### ISSUE THREAD

**Issue by popy** [couchbase/couchbase-lite-android#210]
The problem occurs with Beta2 version of the library on some middle spec professionnal devices like Motorola TC55 and Athesi(Gen2Wave) RP1300 running Android 4.1.2 or Unitech PA700 running Android 4.1.1. I haven't been able to reproduce it on my Nexus 4, I don't know if it's related to it having better hardware specs or it's more recent version of android (4.4.2). 

The context is a database with some small json documents and some big ones. If big documents are inserted first in the database (either a small quantity or thousands), updating the index works, but if they are inserted after the small ones (even just a small quantity like hundreds), it can crash with an error like this one:
```
02-26 14:59:53.300: W/CursorWindow(7637): Window is full: requested allocation 4170 bytes, free space 2736 bytes, window size 2097152 bytes
02-26 14:59:53.300: E/CursorWindow(7637): Failed to read row 1124, column 0 from a CursorWindow which has 1124 rows, 5 columns.
02-26 14:59:53.310: W/Database(7637): Failed to rebuild view TestView: 500
02-26 14:59:53.310: I/CBLSQL(7637): main CANCEL transaction (level 1)
02-26 14:59:53.310: W/dalvikvm(7637): threadid=1: thread exiting with uncaught exception (group=0x41d34438)
02-26 14:59:53.310: E/AndroidRuntime(7637): FATAL EXCEPTION: main
02-26 14:59:53.310: E/AndroidRuntime(7637): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testcouchbase/com.example.testcouchbase.MainActivity}: java.lang.IllegalStateException: Couldn't read row 1124, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2108)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread.access$600(ActivityThread.java:142)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.os.Looper.loop(Looper.java:137)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread.main(ActivityThread.java:4875)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at java.lang.reflect.Method.invoke(Method.java:511)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at dalvik.system.NativeStart.main(Native Method)
02-26 14:59:53.310: E/AndroidRuntime(7637): Caused by: java.lang.IllegalStateException: Couldn't read row 1124, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.database.CursorWindow.nativeGetLong(Native Method)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.database.CursorWindow.getLong(CursorWindow.java:507)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.couchbase.lite.storage.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.getLong(AndroidSQLiteStorageEngine.java:183)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.couchbase.lite.View.updateIndex(View.java:488)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.example.testcouchbase.MainActivity.testCouchbase(MainActivity.java:120)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at com.example.testcouchbase.MainActivity.onCreate(MainActivity.java:41)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.Activity.performCreate(Activity.java:5042)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072)
02-26 14:59:53.310: E/AndroidRuntime(7637): 	... 11 more
```
Warnings like "02-26 14:59:53.300: W/CursorWindow(7637): Window is full: requested allocation 4170 bytes, free space 2736 bytes, window size 2097152 bytes"
occurs a lot, wether before crashing or not. I don't know if it's "normal" or if it can cause some problems.

Something very strange is that it doesn't crash if only big documents are inserted in the database (even thousands). 

Here is some code to reproduce the crash, but it won't crash on every device ...
```Java
	String dbName = "testdb";
	File dir = this.getExternalFilesDir(null);
	Manager manager = new Manager(dir, Manager.DEFAULT_OPTIONS);
	// Delete existing database to start the test from an empty one
	manager.getDatabase(dbName).delete();
	final Database database = manager.getDatabase(dbName);
	// Add a view
	View view = database.getView("TestView");
	view.setMap(new Mapper() {
		@Override
		public void map(Map<String, Object> props, Emitter emiter)
		{
		}			 		
	}, "1.0");
	// Load a json documents
	String smallJson = "{\"field\":\"value\"}";
	String json = "{\"another_field1\":\"another_long_valueeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\", \"another_field2\":\"another_long_valueeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\"}";
	ObjectMapper mapper = new ObjectMapper();
	final Map<String,Object> smallproperties = mapper.readValue(smallJson, new TypeReference<HashMap<String,Object>>(){});
	final Map<String,Object> properties = mapper.readValue(json, new TypeReference<HashMap<String,Object>>(){});
	// Add documents in database
	database.runInTransaction(new TransactionalTask() {
		@Override
		public boolean run()
		{
			try
			{
				for(int i=0;i<3000;i++)
				{
					Document doc = database.createDocument();
					doc.putProperties(smallproperties);
				}
				for(int i=0;i<500;i++)
				{
					Document doc = database.createDocument();
					doc.putProperties(properties);
				}
			}
			catch (CouchbaseLiteException e)
			{
				e.printStackTrace();
			}
			return true;
		}				
	});
	// Update view index
	view.updateIndex();
```

I hope you'll find what's going wrong, because we would like to use couchbase lite on our android app for field workers, but this problem prevents us from deploying it.

Thanks :)

**Comment by razorblade446** [comment]
Sorry to bug, but can you explain how to build CBL and SQLite??? Thanks!!!

**Comment by hinesmr** [comment]
For sqlite, must be downloaded from the sqlite source on their website as a single C file (what they call 'amalgamated'.) Then the single C file must be included into the native build of your application. For android, that requires that you either know how to use the NDK (native development kit) by yourself or you have a toolchain that can do it for you (maybe Android's studio).

This will produce a single sqlite3 binary. Then, in Java, you would load that sqlite3.so library with "System.loadLibrary("sqlite3"), which would pick your sqlite version instead of the stock sqlite version that comes with Android.

For iOS, this is a bit easier, because you can easily compile C code directly into your Xcode project without any fuss.

For building CBL ---- there's lots of documentation on google.

**Comment by hideki** [comment]
Hi all, 

We fixed `View.updateIndex()` issue which was caused by `IllegalStateException` from `getLong(int)`.
https://github.com/couchbase/couchbase-lite-java-core/commit/041636a9ad4521ce07f41f141891abd61c801b37

If you still have testable environment for this issue, could you please try latest codes from master branch?

Thanks!
Hideki

**Comment by popy** [comment]
Hi, I just tried it on a device that was crashing for me. Using the master branch and commenting the fix commit modifications makes the updateIndex() to crash as it was when I reported the problem. Second attempt with the fix applied didn't crashed. So it seems your fix is working to prevent the updateIndex() from crashing. One question I have in mind seeing the commit modifications : the fix consists of skipping cursor rows where the first column index returns null, are you sure it won't skip indexing some revisions by skipping rows ? I suppose null rows results of a problem while trying to load it in memory, so I'm wondering if those rows are loaded as the next one when this problem occurs.

Another remark is that while it doesn't crash anymore, I still see a lot of "Window is full" warnings, and it seems it slows down the indexing, even more when using big documents in big quantities. I'll try to investigate this a little more and come back to you, but I think preventing those waring should improve indexing performance. Maybe trying to limit requests results to the CurorWindow limit of 2097152 bytes would resolve it, but it would require to process indexing in multiple sql calls.

**Comment by popy** [comment]
After digging a little more, I can confirm that the fix prevents the indexing from crashing but makes the impacted revisions (those not properly loaded into the cursor, making getLong(0) to return null) not to be indexed at all.

As for now, it seems to me the only solution would be to split indexing in chunks smaller than the cursor window to prevent memory problems. It should speed up the indexing with big amount of revisions and big documents too, but the problem would be to determine how big each chunk should be, depending on the size of documents the user is using...

**Comment by hideki** [comment]
Hi @popy,
 
Thank you very much for your feedbacks. 

This issue might be caused by size of json field and number of query results. These consume a lot of memory, and might cause 'null' field issue.
https://github.com/couchbase/couchbase-lite-java-core/blob/041636a9ad4521ce07f41f141891abd61c801b37/src/main/java/com/couchbase/lite/View.java#L516
```
"SELECT revs.doc_id, sequence, docid, revid, json, no_attachments, deleted FROM revs, docs WHERE sequence>? AND current!=0 "
```

Releasing the json and properties variables as soon as possible might reduce the chance to encounter the memory issue.

Can I ask you a favor?
If you run your code on latest Android OS (ex API 21), can you find a record in maps table that are not indexed with Android device you encountered the issue? Android emulator is fine for this test. 

Thanks!

**Comment by hideki** [comment]
Hi @popy,
I have another question. Are you using CBL Android from master branch?
https://github.com/couchbase/couchbase-lite-java-core/issues/502 might reduce memory usage during `View.updateIndex()`. CBL uses custom collator for JSON field and RevisionID field. During `View.updateIndex()`, SQLite calls custom collator to make SQLite index for maps table. By version 1.0.4, custom collator (Native library) for JSON field always calls Java's collator internally. It makes `View.updateIndex()` slower. I assume it also consumes a lot of memory if JSON is large because of JNI interface. From above reason, if you are not using master branch, could you please try master branch version of CBL? This might reduce the chance to encounter the problem. If you are using gradle from Android Studio, please use version "0.0.0-511" http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-511/ .
Thanks!
Hideki

**Comment by popy** [comment]
Hi @hideki,

All my tests were done using the latest master branch. On problematic devices (older API version) it doesn't crash thanks to the fix, but rows that contains null value are not indexed. On a more recent device (Samsung Galaxy S5) with latest Android version, there isn't any row with null values so all documents are indexed properly, but when using big documents there is still a lot of "Window is full" warnings, not causing any crash but slowing the indexing process.

Until now we weren't using Sync Gateway, so with our manual sync process we where inserting docs by batch (with data smaller than the CursorWindow memory) then indexing them before the next batch to reduce performance problems and avoid crashes on older Android API versions. Now we want to use Sync Gateway, so we get all documents before to update our views index, preventing us from indexing by batch.

I tried to create a modified version of updateIndex method to process documents by batches, it required to rethink the sql request to get only the last revision of each documents (in order to avoid processing duplicated doc_id within different batches) ordered by sequence in ascendant order, to be able to know the last sequence processed on each loop. It was quicker will a small amount of documents but longer with more of them. The bottleneck was the time used to request the database for each loop, maybe it can be improved by changing some indexes in the database (I'm really not an expert on db indexes :)) You can take a look here: https://gist.github.com/popy/2b10eacd711228544c4c

**Comment by hideki** [comment]
Hi @popy,

Thank you very much for `updateIndex()` with batch solution. In general, I believe it works well.

1) Suggestion: you need to add following code at line 111 to your gist code
https://github.com/couchbase/couchbase-lite-java-core/blob/53487f143903cb0889df304c71c046b3177df920/src/main/java/com/couchbase/lite/View.java#L550-L555
```
while ((keepGoing = cursor.moveToNext()) && (cursor.isNull(0) || cursor.getLong(0) == docID)) {
   // Skip rows with the same doc_id -- these are losing conflicts.
}
``` 

2) Best brachCount depends on JSON document sizes. For example, in case each JSON document size is around 10K byte, batchCount could be around 20 because of 2MB Android SQLite limitation.

3) Another potential solution: Eliminate json field from SQL query (https://github.com/couchbase/couchbase-lite-java-core/blob/53487f143903cb0889df304c71c046b3177df920/src/main/java/com/couchbase/lite/View.java#L517). Then query json value just before calling `map()` (https://github.com/couchbase/couchbase-lite-java-core/blob/53487f143903cb0889df304c71c046b3177df920/src/main/java/com/couchbase/lite/View.java#L517). This might reduce memory usage.

4) I have observed CursorWindow memory warning if app consumes a lot of memory in general. If we could reduce peak memory usage from other area, it might solve the issue.

5) Question: This issue is hard to reproduce. It depends on document. Is it possible to access your data?

Thanks,
Hideki

**Comment by popy** [comment]
Hi @hideki,

Concerning your first point, I think it shouldn't be required to skip duplicate documents id because they are filtered to the last sequence for each document in the sql request, but maybe I'm wrong ?

I already thinked about retrieving the json field just before to call the map method, but I thought it would induce too much sql requests and take more time than other solutions. I will test it anyway to be sure.

Concerning the data I use for my tests it's just generated data. I just uploaded a test app with (ugly) code here : https://github.com/Kawet/couchbase-lite-android-tests if you want to take a look. The "init db" button deletes the database before recreating it and inserted documents with size and quantities as requested. Index buttons deletes the index before to update it. Batch count is set to 200. I observed very various index update timings using different settings, it seems using very small docs amplifies the memory problems (like 50 chars value in settings for small docs and more than 8000 for big ones).

**Comment by hideki** [comment]
Hi @popy,

If you documents don't have conflicts, you might not need the code to skip. Otherwise, it requires to avoid duplicated index.

Thanks for your test app.

**Comment by hideki** [comment]
I will reopen this ticket. 

Current status:
- Crash issue was solved by checking if the field is null.
- Heavy memory usage causes the null field. And it causes missing index

**Comment by popy** [comment]
I added a version of updateIndex which gets the json field separately just before to call map() in my test app. It seems to be a just little slower for small documents in small quantities than original version and batched version, but a lot quicker with a lot of documents and big documents.

I tried with 50000 0.5k + 50000 10k docs and it updated an index that just emits big documents id in less than 3 minutes. I didn't even let the index fully update with other versions because it was too long. The original version seems to be exponentially longer when indexing more and more documents because of CursorWindow memory errors, taking like forever to update the index). 

On my Samsung Galaxy S5 I still see one warning for CursorWindow memory, I will test tomorrow on my other device that uses to crash when updating index to see if this warning can cause a revision not to be indexed and let you know.

**Comment by hideki** [comment]
HI @popy,
Thank you very much for testing the scenario that isolates JSON from original SQL.
Test result makes sense. I have observed that Android system tries to release memory under high memory usage. It makes an application significantly slow. Thanks again!

**Comment by popy** [comment]
A little late but I finally tried it on the device that was initially crashing while updating index. So with the new solution that gets json just before to call map() all documents are indexed. The memory warning from CursorWindow at the beginnning is still present but seems not to be a problem (maybe because it just occurs once and not a lot of times)

**Comment by hideki** [comment]
Hi @popy, Thank you very much for your updates! It is wonderful!

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-java-core/pull/591

**Comment by hideki** [comment]
Hi @popy,

We committed and merged new solution into release/1.1.0 branch.

Brief description of solution:
1. Isolates json field from original query 
1. Retrieves json  field just before map function

 https://github.com/couchbase/couchbase-lite-java-core/commit/ef307a06c88a7acd9f3b31cf171f8e6b1ea5c1a7

Release/1.1.0 branch: https://github.com/couchbase/couchbase-lite-java-core/tree/release/1.1.0

When you have time, could you please try CBL Android from release/1.1.0 branch?

Thanks!

**Comment by popy** [comment]
Hi @hideki,

I just tried the release/1.1.0 branch with both devices (Samsung Galaxy S5 and Unitech PA 700 that was crashing before first fix for null values then missing some indexed documents) using various documents count, and everything is ok. All documents are indexed, no crash, and indexing a lot of documents is a lot quicker than before.

Thanks for the fix :)

**Comment by hideki** [comment]
Hi @popy,

Thank you very much for testing release/1.1.0 branch. And I am glad that we collaboratively could solve this critical issue. Regarding indexing performance, lowering peak memory usage during indexing by this fix is effective. And also, we found there was one of bottle-necks in our custom collator. Fixing collator made indexing speed faster.

Have a wonderful day!
Hideki

**Comment by bundeeteddee** [comment]
@hideki , just checking if this is in master as well or just in the release/1.1.0 branch?

**Comment by hideki** [comment]
This fix is in both release/1.1.0 and master. Actually, release/1.1.0 and master are almost identical.

**Comment by bundeeteddee** [comment]
Ah i see. I am not too sure if this is related.

This is what i'm seeing this on the logger:
    W/Sync﹕ Error converting lastSequence: null to long.  Using 0
    W/CursorWindow﹕ Window is full: requested allocation 304 bytes, free space 28 bytes, window size 2097152 bytes
    W/CursorWindow﹕ Window is full: requested allocation 72 bytes, free space 48 bytes, window size 2097152 bytes
    I/art﹕ Background partial concurrent mark sweep GC freed 151301(13MB) AllocSpace objects, 2(541KB) LOS objects, 39% free, 7MB/13MB, paused 2.983ms total 104.942ms
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 4.0 seconds.
    Connections: 0 active, 1 idle, 0 available.
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 8.001 seconds.
    Connections: 1 active, 0 idle, 0 available.
    Requests in progress:
    executeForCursorWindow started 0ms ago - running, sql="SELECT json FROM revs WHERE sequence=?"
    W/SQLiteConnectionPool﹕ The connection pool for database '+data+data+com_xxx+files+xxxx_cblite' has been unable to grant a connection to thread 20710 (CBLRequestWorker-f74e7-0) with flags 0x1 for 12.002001 seconds.
    Connections: 0 active, 1 idle, 0 available.

A bit of backstory to this: I've replicated this database that is around 108k document large. That went well, and after replication i invoke the view creation process (calling some functions for the first time that uses the views that i want created in the setup process), this is where the warnings are coming up.

Most of the documents are quite small, the largest i can tell is about 500kb document (about 2 or them), where the rest are < 10kb. 

I went obtained a copy of the sqlite database, where i can see about 230k rows, to check on "revs" tablet on "json" column to see if there are anything that is more than 2mb in size (there are none). Is this related to this issue?

**Comment by hideki** [comment]
Hi @bundeeteddee,

Thank you for your report.

From the log message you posted, the problem you are encountering is related with this issue. The problem could be in [View.updateIndex()](https://github.com/couchbase/couchbase-lite-java-core/blob/b73ee4f100b7f68a79c567b3c2e4d27e641fc4ef/src/main/java/com/couchbase/lite/View.java#L434), or we need to optimize `updateIndex()` further for memory usage.

230K revision records in revs table is a lot.

I have two questions to understand the problem
- How many documents in the database? I'd like to average number of revisions per document.
- What kind of device or emulator settings are you using for your test? 800MB? 1GB? 2GB? or 3GB memory device? If you are using low-end device, it could easily encounter this memory problem.

Thanks!

**Comment by bundeeteddee** [comment]
Hi @hideki thanks for getting back so quickly.

There are about 108k documents in the couch database :)

Regarding device, i'm on Samsung Galaxy Tab A actual device, so its a 1.2G machine with 2gb RAM size. I have replicated with smaller databases ranging from 400 documents to 20k documents are doing fine as far as i have seen. 

From your comment, it seems this is to do with the total amount of revision records and not the limit on each record size?

Thanks again!

**Comment by hideki** [comment]
Hi @bundeeteddee,

- Average revisions per document is 2. It is common.
- 2GB RAM is one of high-end device

It seems problem is caused by number of documents (revisions). 

I forgot to ask in previous comment. Is your map function is complicated? or simple? If you can share, can you share the map function?

Thanks,
Hideki

**Comment by bundeeteddee** [comment]
Hi @hideki 

For sure, the map function as follows:
`<addr>`
View patientIdView = db.getView(String.format("%s/%s", patientDesignDocName, patientByIdView));
        Boolean check = patientIdView.setMapReduce(new Mapper() {

            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Object type = document.get("type");
                if (type != null && type.toString().equals("patient")) {
                    emitter.emit(document.get("_id").toString(), document);
                }
            }
        }, null, "1.0");
`<addr>`

And my patient document has about 20-25 fields i would think.

Thanks!

**Comment by hideki** [comment]
Hi @bundeeteddee,

Your map function is simple. I believe it does not cause any problem.

I created [new ticket for this issue](https://github.com/couchbase/couchbase-lite-java-core/issues/654). 
I will track this by new ticket.
