### ISSUE TITLE
Android P2P Replication not working

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-android#497]
According to a [forum post](https://forums.couchbase.com/t/couchbase-lite-mobile-peer-to-peer-replication/2591/6), P2P Replication (tested via 2 emulators, nexus 5 and 6) doesn't work.

One thing that I quickly found out is the Router class doesn't route _session message right based on the current master as of 01/20 (0c502e9a3abe20126596f642bf7fac6570f8e04b):

Env: A listener running on port 10000. A redirection is set as redir add tcp:5000:10000
Test URL: http://10.0.2.2:5000/db/_session 
Result: {"error":"not_found","reason":"Router unable to route request to do_GET_Document_session"}

**Comment by steffar** [comment]
With regards to this bug, is there a quick fix-around for this?

Thanks.

**Comment by hideki** [comment]
@steffar  So far, we could not find time to investigate this issue. We will try to investigate this issue as soon as possible. Thank you for your patience.

**Comment by AlexInHFUT** [comment]
Have you solve this problem? I also really interested in peer-to-peer replication on Android.

**Comment by hideki** [comment]
@AlexInHFUT As many community developers are interested in peer-to-peer feature, we will investigate this issue as soon as possible. Thank you very much for your patience.

**Comment by pasin** [comment]
Sorry I clicked a wrong button. I didn't mean to close the issue. The _session message is sent only when there is an authenticator set to the replicator. So I think if there is no authenticator, the android P2P should be working just fine. We will need to fix the _session message anyway.

**Comment by pasin** [comment]
Closing this issue. Please follow these 2 issues instead:
https://github.com/couchbase/couchbase-lite-java-core/issues/426
https://github.com/couchbase/couchbase-lite-java-core/issues/427

**Comment by steffar** [comment]
I took the advice mentioned in #497 with regards to the authentication and the replicator:
<i>"The _session message is sent only when there is an authenticator set to the replicator. So I think if there is no authenticator, the android P2P should be working just fine. "</i>

I tried omitting the authenticator from the replicator, but the LiteListener() requires <i>allowedCredentials</i>.  Following is the constructor of LiteListener():
<i>new LiteListener(manager, suggestedListenPort, allowedCredentials)</i>

I tried setting the allowedCredentials to null when initialising the LiteListener on the server, and not setting any authentication credentials on the peer, but I get the warning <i>authHeader is null</i> in the server, while the peer client gets a <i>404 not found</i> error.

I also tried setting the basic authentication credentials in the URL (as mentioned in http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/replication/index.html), however in this case I also get the 404 error.

Can you please advise how the authentication can be switched off?

**Comment by hideki** [comment]
#426 Error when sending /db/_session message to Router was fixed and merged in master yesterday.  Could you please try this with master branch?

**Comment by steffar** [comment]
I have tested this issue using the master branch on a Couchbase device A
(serving as the server) and using both 1.0.3 and 1.0.4 on a peer client
device B.

Using 1.0.4 on the peer I don't get the 404 not found error  but I get
a *"Cannot
parse version code" error* (on 1.0.3 I do get the 404 error) I don't think
the sync is working correctly because I get an error "*PullerInternal
stopGraceful.run() finished".*

Following is the stack trace:
02-14 08:32:57.730    1710-1710/couchbase.examples.com.couchbasemobilepeer
E/CBLite? Cannot parse version code:
02-14 08:32:57.730    1710-1710/couchbase.examples.com.couchbasemobilepeer
E/CBLite? Cannot parse version code:
02-14 08:32:57.960    1710-1710/couchbase.examples.com.couchbasemobilepeer
I/HelloWorld? PullReplication
02-14 08:32:57.960    1710-1710/couchbase.examples.com.couchbasemobilepeer
I/HelloWorld? PushReplication
02-14 08:32:58.200    1710-1710/couchbase.examples.com.couchbasemobilepeer
D/? HostConnection::get() New Host Connection established 0xb8aea6f0, tid
1710
02-14 08:32:58.440    1710-1758/couchbase.examples.com.couchbasemobilepeer
E/Sync? com.couchbase.lite.replicator.ReplicationInternal$4@b1064220
checkSessionAtPath() response: {userCtx={roles=[_admin], name=null},
ok=true}
02-14 08:32:58.460    1710-1710/couchbase.examples.com.couchbasemobilepeer
W/EGL_emulation? eglSurfaceAttrib not implemented
02-14 08:32:58.460    1710-1710/couchbase.examples.com.couchbasemobilepeer
D/OpenGLRenderer? Enabling debug mode 0
02-14 08:32:58.510    1710-1758/couchbase.examples.com.couchbasemobilepeer
W/Sync? com.couchbase.lite.replicator.PullerInternal@b1019d48: starting
ChangeTracker with since=null mode=OneShot
02-14 08:32:58.510    1710-1758/couchbase.examples.com.couchbasemobilepeer
W/Sync? com.couchbase.lite.replicator.PullerInternal@b1019d48: started
ChangeTracker com.couchbase.lite.replicator.ChangeTracker@b1064538
02-14 08:32:58.570    1710-1762/couchbase.examples.com.couchbasemobilepeer
W/ChangeTracker? com.couchbase.lite.replicator.ChangeTracker@b1064538:
Change tracker calling stop (OneShot)
02-14 08:32:58.570    1710-1762/couchbase.examples.com.couchbasemobilepeer
W/ChangeTracker? com.couchbase.lite.replicator.ChangeTracker@b1064538:
Change tracker calling changeTrackerStopped, client:
com.couchbase.lite.replicator.PullerInternal@b1019d48
02-14 08:32:58.580    1710-1764/couchbase.examples.com.couchbasemobilepeer
W/ChangeTracker? com.couchbase.lite.replicator.ChangeTracker@b1064538:
Change tracker not calling changeTrackerStopped, client == null
02-14 08:32:58.580    1710-1764/couchbase.examples.com.couchbasemobilepeer
E/Sync? PullerInternal stopGraceful.run() finished

**Comment by steffar** [comment]
Replication seems to be working fine now; I no longer get the error 404 not found.

**Comment by SunilDhaker** [comment]
Hii  @steffar  !  How did you fixed the issue this issue , I am still getting "Router unable to route request to do_GET_Document_all_doc" error . I am compiling latest version of couchbase lite and couchbase lite java listner  i.e. 
''' compile 'com.couchbase.lite:couchbase-lite-android:1.1.0-532'
   compile 'com.couchbase.lite:couchbase-lite-java-listener:1.1.0-532'  '''

Please help me to resolve this problem '
Thanks ,

**Comment by steffar** [comment]
Hi Sunil

To overcome this issue I used the latest version of the couchbase-lite framework, as follows:
```
compile 'com.couchbase.lite:couchbase-lite-android:1.0.4'
compile 'com.couchbase.lite:couchbase-lite-java-core:1.0.4'
compile 'com.couchbase.lite:couchbase-lite-java-listener:1.0.4'
```

However it seems that you are using newer versions of the framework, so your issue might be due other reasons.

**Comment by SunilDhaker** [comment]
Yah Steffar , First of all thanks for replying I think issue is somewhat in sync from client . I am able to get all docs when I open url (TCP:port/<db>/_all_docs) in browser but on android the documents are not syncing . Here is how I am doing it 
Starting server on one device like : 
```javascript
    liteListner = new LiteListener(manager , port , new Credentials("foo" , "bar"));
    liteListner.start();
```

And on client side 
```javascript
                syncUrl = "http://192.168.3.201:59840/barrickrdc"
                pullReplication = database.createPullReplication(syncUrl);
                pullReplication.setContinuous(false);
                pushReplication = database.createPushReplication(syncUrl);
                pushReplication.setContinuous(false);
                Authenticator basicAuthenticator =AuthenticatorFactory.createBasicAuthenticator(username, password);
            pullReplication.setAuthenticator(basicAuthenticator);
            pushReplication.setAuthenticator(basicAuthenticator);
            pullReplication.start();
            pushReplication.start();
```

Am I doing it ryt ? 
This code should replicate/merge documents in database (if no conflict )  but when I'm doing this nothing is syncing its just showing """com.couchbase.lite.replicator.Replication@41e3ed30 Transition: STOPPING -> STOPPED Total changes: 0 Completed changes: 0 """. But I have unique document in both database.

**Comment by steffar** [comment]
That seems to be the correct code.  Usually whenever I see the message: """com.couchbase.lite.replicator.Replication@41e3ed30 Transition: STOPPING -> STOPPED Total changes: x Completed changes: x """ it is because replication was successful.  

Does continuous replication work?

**Comment by SunilDhaker** [comment]
It worked  :)  I just cloned latest source code(all 3 libraries) and replaced maven dependencies with modules dependencies and it works like charm .
Still Not sure what the problem was (May be some  IDE issue in invalidating cache )  Anyway thanks for your support .
