### ISSUE TITLE
Arabic langs migrate from 1.2.x to 1.3.x

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#966]
Hi @hideki, 

we want to migrate our app from 1.2.x to 1.3.x couchDB, but now we found a big issue.

relevant issue: https://github.com/couchbase/couchbase-lite-android/issues/880

1.2.x didn't support Aracic langs (due to error in replication which we report).
It's fixed now, but with this error was related next one with: 

`Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_١ (code 1):` maps_X is arabic character.

But what happen now:
- User use Arabic/Persian language in phone
- User used old couchDB 1.2.x in app
- Couch db create a table with name `maps_١` which works (because he don't switch to non-arabic lang)
- no user data was synced due to error with: bedarg: ١-524d55825877d7e4b46f01ed56fe98c9 (first character is persian, not EN one 1 character) - it's fixed in 1.3.x
- now we upgrade to 1.3.x which fix `maps_١`, but it require table: maps_1, but for arabic language there is no table maps_1! It's maps_١. And app crash on it.

We have no solution now, how to fix this, because user hasn't backed up data on main couchDB due to replication error in 1.2.x

Solution should be I think:
Look that exists: maps_١, if exists rename it on: maps_1 and not crash.

```
Process: com.droid4you.application.wallet, PID: 16040
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droid4you.application.wallet/com.droid4you.application.wallet.activity.MainActivity}: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2491)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2564)
    at android.app.ActivityThread.access$800(ActivityThread.java:170)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5576)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
 Caused by: com.couchbase.lite.internal.database.sqlite.exception.SQLiteException: no such table: maps_1 (code 1): , while compiling: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?
    at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:718)
    at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:431)
    at com.couchbase.lite.internal.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:595)
    at com.couchbase.lite.internal.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:64)
    at com.couchbase.lite.internal.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
    at com.couchbase.lite.internal.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
    at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1300)
    at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1239)
    at com.couchbase.lite.storage.SQLiteStorageEngineBase.rawQuery(SQLiteStorageEngineBase.java:183)
    at com.couchbase.lite.store.SQLiteViewStore.runQuery(SQLiteViewStore.java:1010)
    at com.couchbase.lite.store.SQLiteViewStore.regularQuery(SQLiteViewStore.java:623)
    at com.couchbase.lite.View.query(View.java:358)
    at com.couchbase.lite.Database.queryViewNamed(Database.java:2194)
    at com.couchbase.lite.Query.run(Query.java:446)
```

Note to self: 792

**Comment by mtrakal** [comment]
Test scenario:
- set phone to Arabic/Persian lang
- use coucDB 1.2.x
- create couchDB object (internally create maps_١)
- upgrade in project couchDB to 1.3.x
- app crash on: no such table: maps_1

**Comment by pasin** [comment]
@hideki have we fixed this in 1.3.0?

**Comment by hideki** [comment]
We fixed this issue in 1.3.0. 

@mtrakal 
Could you please confirm if this issue is already addressed?

**Comment by mtrakal** [comment]
Hi,  @hideki, @pasin

No, migration from 1.2.x to 1.3.x is not working. 
When you start from 1.3.x from begining it's ok,  but not when you migrate from old database. 

See please scenario in my second comment. It's different scenario from scenario described in #880

**Comment by mtrakal** [comment]
Moře detailed :
- switch lang in phone to arabic 
- first time run app (or delete app data), no created  database 
- start app with couch 1.2.x
- continue by scenario in my original second comment

**Comment by mtrakal** [comment]
It's caused by `view` which we created, and solution is, set new version of this view. But without change the version it still crash.

```
View view = getDatabase().getView(NON_RECORD_ITEMS_VIEW_NAME);
        view.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
               ...
                }
            }
        }, "1");
        return view.createQuery();
```

When upgrade to 1.3.x just upgrade version of view fix this issue. From `"1"` to `"2"`

**Comment by mtrakal** [comment]
Next issue after upgrade is, that original objects have first revision stored in local couch which looks like:  `١-524d55825877d7e4b46f01ed56fe98c9` (start with ١ arabic representation of 1).
This object is never synced to backend couchDB (due to character in revision). But this objects are not synced neither after upgrade. Because a arabic/persian character is still in revision (or previous revision when you update object).

This could have solution like:
- check current revision, 
- if current revision contains non-english character
- update object revision 
- purge old revisions.

**Comment by hideki** [comment]
Hi @mtrakal,
Sorry for slow reply.
As workaround, can your app delete index when app migrates? Then the app could re-index data.
Thanks!
Hideki

**Comment by mtrakal** [comment]
Hi @hideki ,

for first issue we just increase version of view to `2`. It works.

For the second issue I created this method for migration, it's not much optimized, but looks as working for us.
It could throw OOM when there will be much documents, and maybe another issues, but we need to fix it asap for Arabic/Persian.
After migration we set `setMaxRevTreeDepth` to default 20.
```
    public void fixArabicObjects(final PersistentConfig persistentConfig, final OttoBus ottoBus) {
        new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... params) {
                Query allDocumentsQuery = getDatabase().createAllDocumentsQuery();
                allDocumentsQuery.setAllDocsMode(Query.AllDocsMode.ALL_DOCS);
                try {
                    QueryEnumerator rows = allDocumentsQuery.run();
                    int count = rows.getCount();
                    if (count > 0) {
                        int current = 0;
                        final ArrayList<UnsavedRevision> unsavedRevisions = new ArrayList<>();
                        while (rows.hasNext()) {
                            QueryRow queryRow = rows.next();
                            Document document = queryRow.getDocument();
                            String revisionNumber = document.getCurrentRevisionId().split("-")[0];
                            boolean convert;
                            try {
                                // check that number us in english format and not arabic
                                long originalNumber = Long.parseLong(revisionNumber);
                                String englishNumber = String.valueOf(originalNumber);
                                convert = !englishNumber.equals(revisionNumber);
                            } catch (NumberFormatException eN) {
                                eN.printStackTrace();
                                convert = true;
                            }

                            if (convert) {
                                UnsavedRevision newRevision = document.createRevision();
                                unsavedRevisions.add(newRevision);
                            }
                            current++;
                        }
                        getDatabase().runInTransaction(new TransactionalTask() {
                            @Override
                            public boolean run() {
                                for (UnsavedRevision unsavedRevision : unsavedRevisions) {
                                    try {
                                        unsavedRevision.save();
                                    } catch (CouchbaseLiteException e) {
                                        e.printStackTrace();
                                    }
                                }
                                return true;
                            }
                        });
                        try {
                            Database database = getDatabase();
                            // maybe use purge revisions
                            database.setMaxRevTreeDepth(1);
                            database.compact();
                            persistentConfig.setCouchDb12x13xMigrationComplete();
                        } catch (CouchbaseLiteException e) {
                            e.printStackTrace();
                        }
                    } else {
                        persistentConfig.setCouchDb12x13xMigrationComplete();
                    }
                } catch (CouchbaseLiteException e) {
                    e.printStackTrace();
                }
                return null;
            }
        }.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
    }
```

**Comment by hideki** [comment]
Hi @mtrakal,
Thank you for sharing your workaround solution.
As you have a workaround solution for this, we will not fix this.
